# Experience calculation configuration
# required experience is calculated: level * (base * exponent) + base
experience:
 base: 100 # default value of base exp (integer)
 exponent: 0.2 # default value of exponent (double)
 petname:
  base: 150 # type-specific value of base exp
  exponent: 1.5 # type-specific value of exponent

gain:
 entities:
  zombie: 2
 blocks:
  dirt: 2








