# Experience calculation configuration
# required experience is calculated: level * (base * exponent) + base
experience:
 base: 100 # default value of base exp (integer)
 exponent: 0.2 # default value of exponent (double)
 petname:
  base: 150 # type-specific value of base exp
  exponent: 1.5 # type-specific value of exponent

gain:
 entities:
  zombie: 2
 blocks:
  dirt: 2

# Reward configuration
# format action; body
# actions: msg, cmd, sound
rewards:
 general: # executed every level for every pet
  - "msg;You leveled up, you new level is {LVL}"
 1: # executed on lvl 1 for every pet
  - "cmd; give {PLAYER} minecraft:iron_hoe"
 petname: # executed on lvl 1 for pet named "petname"
  1:
   - "msg;you aint getting nothing"








